/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_5.view;
import com.mycompany.proyecto_5.dao.AsientoDAO;
import com.mycompany.proyecto_5.dao.FuncionDAO;
import com.mycompany.proyecto_5.dao.ReservaDAO;
import com.mycompany.proyecto_5.dao.UsuarioDAO;
import com.mycompany.proyecto_5.model.Asiento;
import com.mycompany.proyecto_5.model.Usuario;
import com.mycompany.proyecto_5.service.ReservaService;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author LENOVO
 */
public class FrmReservas extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmReservas.class.getName());
    
     private final FuncionDAO funcionDAO         = new FuncionDAO();
    private final UsuarioDAO usuarioDAO         = new UsuarioDAO();
    private final AsientoDAO asientoDAO         = new AsientoDAO();
    private final ReservaDAO reservaDAO         = new ReservaDAO();
    private final ReservaService reservaService = new ReservaService();
 
    private int asientoSeleccionadoId = -1;
    private final Map<Integer, javax.swing.JButton> botonesAsiento = new HashMap<>();
 
    private static final Color COLOR_LIBRE   = new Color(70, 180, 70);
    private static final Color COLOR_OCUPADO = new Color(200, 50, 50);
    private static final Color COLOR_SELEC   = new Color(50, 100, 220);

    /**
     * Creates new form FrmReservas
     */
    public FrmReservas() {
        initComponents();
        setSize(1050, 900);
        setLocationRelativeTo(null);
        setResizable(false);
        
          btnCancelar.addActionListener(e -> cancelar());
        btnVolver.addActionListener(e -> {
            new FrmPrincipal().setVisible(true);
            this.dispose();
        });
 
        cargarCombos();
        actualizarPanelAsientos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbFunciones = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbUsuarios = new javax.swing.JComboBox<>();
        panelAsientos = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnReservar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESERVA DE ASIENTOS");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("Función:");

        cmbFunciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFunciones.addActionListener(this::cmbFuncionesActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setText("Usuario:");

        cmbUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        panelAsientos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelAsientosLayout = new javax.swing.GroupLayout(panelAsientos);
        panelAsientos.setLayout(panelAsientosLayout);
        panelAsientosLayout.setHorizontalGroup(
            panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        panelAsientosLayout.setVerticalGroup(
            panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnVolver.setText("Volver");

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCancelar.setText("Cancelar Reserva");

        btnReservar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnReservar.setText("Reservar Asiento");
        btnReservar.addActionListener(this::btnReservarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(543, 543, 543)
                        .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReservar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(cmbFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        reservar(); 
    }//GEN-LAST:event_btnReservarActionPerformed

    private void cmbFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFuncionesActionPerformed
        actualizarPanelAsientos(); 
    }//GEN-LAST:event_cmbFuncionesActionPerformed
    
    
    private void cargarCombos() {
        cmbFunciones.removeAllItems();
        for (String f : funcionDAO.listarFunciones())
            cmbFunciones.addItem(f);
 
        cmbUsuarios.removeAllItems();
        for (Usuario u : usuarioDAO.listarUsuarios())
            cmbUsuarios.addItem(u.getIdUsuario() + " - " + u.getNombre());
    }
    
    private void actualizarPanelAsientos() {
         panelAsientos.setLayout(null);
        panelAsientos.removeAll();
        botonesAsiento.clear();
        asientoSeleccionadoId = -1;
 
        int idFuncion = obtenerIdFuncionSeleccionada();
        if (idFuncion < 0) {
            panelAsientos.revalidate();
            panelAsientos.repaint();
            return;
        }
 
        int idSala = funcionDAO.obtenerIdSala(idFuncion);
        if (idSala < 0) {
            panelAsientos.revalidate();
            panelAsientos.repaint();
            return;
        }
 
        List<Asiento> asientos = asientoDAO.asientosPorSala(idSala);
        List<Integer> ocupados = asientoDAO.asientosOcupados(idFuncion);
 
        // Agrupar asientos por fila (A, B, C...)
        Map<String, List<Asiento>> porFila = new java.util.LinkedHashMap<>();
        for (Asiento a : asientos)
            porFila.computeIfAbsent(a.getFila(), k -> new java.util.ArrayList<>()).add(a);
 
        panelAsientos.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(3, 3, 3, 3);
 
        int row = 0;
        for (Map.Entry<String, List<Asiento>> entry : porFila.entrySet()) {
            gbc.gridx = 0;
            gbc.gridy = row;
            javax.swing.JLabel lbl = new javax.swing.JLabel(entry.getKey());
            lbl.setFont(new Font("Segoe UI", Font.BOLD, 12));
            panelAsientos.add(lbl, gbc);
 
            int col = 1;
            for (Asiento a : entry.getValue()) {
                boolean ocupado = ocupados.contains(a.getIdAsiento());
                javax.swing.JButton btn = new javax.swing.JButton(String.valueOf(a.getNumero()));
                btn.setPreferredSize(new Dimension(45, 35));
                btn.setFont(new Font("Segoe UI", Font.PLAIN, 11));
                btn.setBackground(ocupado ? COLOR_OCUPADO : COLOR_LIBRE); // rojo u ocupado
                btn.setForeground(Color.WHITE);
                btn.setOpaque(true);
                btn.setBorderPainted(false);
                btn.setEnabled(!ocupado); // deshabilitado si esta ocupado
                final int id = a.getIdAsiento();
                btn.addActionListener(e -> seleccionarAsiento(id));
                botonesAsiento.put(a.getIdAsiento(), btn);
                gbc.gridx = col;
                gbc.gridy = row;
                panelAsientos.add(btn, gbc);
                col++;
            }
            row++;
        }
 
        panelAsientos.revalidate();
        panelAsientos.repaint();
    }
    
     private void seleccionarAsiento(int idAsiento) {
        if (asientoSeleccionadoId >= 0 && botonesAsiento.containsKey(asientoSeleccionadoId))
            botonesAsiento.get(asientoSeleccionadoId).setBackground(COLOR_LIBRE);
        asientoSeleccionadoId = idAsiento;
        botonesAsiento.get(idAsiento).setBackground(COLOR_SELEC);
    }
     
      private void reservar() {
        int idFuncion = obtenerIdFuncionSeleccionada();
        int idUsuario = obtenerIdUsuarioSeleccionado();
        if (idFuncion < 0 || idUsuario < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona función y usuario válidos.");
            return;
        }
        if (asientoSeleccionadoId < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un asiento en el mapa.");
            return;
        }
        String resultado = reservaService.reservarAsiento(idUsuario, idFuncion, asientoSeleccionadoId);
        javax.swing.JOptionPane.showMessageDialog(this, resultado);
        actualizarPanelAsientos(); // refresca el mapa tras reservar
    }
      
       private void cancelar() {
        int idUsuario = obtenerIdUsuarioSeleccionado();
        if (idUsuario < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un usuario válido.");
            return;
        }
        String input = javax.swing.JOptionPane.showInputDialog(this, "ID de la reserva a cancelar:");
        if (input == null || input.isBlank()) return;
        try {
            boolean ok = reservaDAO.cancelarReserva(Integer.parseInt(input.trim()), idUsuario);
            javax.swing.JOptionPane.showMessageDialog(this,
                ok ? "Reserva cancelada." : "No se pudo cancelar. Verifica el ID.");
            actualizarPanelAsientos(); // refresca el mapa tras cancelar
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID inválido.");
        }
    }
       
        private int obtenerIdFuncionSeleccionada() {
        Object sel = cmbFunciones.getSelectedItem();
        if (sel == null) return -1;
        try { return Integer.parseInt(sel.toString().split(" - ")[0].trim()); }
        catch (NumberFormatException e) { return -1; }
    }
        private int obtenerIdUsuarioSeleccionado() {
        Object sel = cmbUsuarios.getSelectedItem();
        if (sel == null) return -1;
        try { return Integer.parseInt(sel.toString().split(" - ")[0].trim()); }
        catch (NumberFormatException e) { return -1; }
    }
    
    
    
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmReservas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbFunciones;
    private javax.swing.JComboBox<String> cmbUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelAsientos;
    // End of variables declaration//GEN-END:variables
}
